require("config.options")
require("config.keymaps")
require("just").setup()
require("integrations").setup()
require("config.session")
require("config.diagnostics")
require("config.autocmds")
require("config.lsp")
